taler_payments.settings:
  type: config_object
  label: 'Taler Payments settings'
  mapping:
    taler_base_url:
      type: uri
      label: 'Taler Base URL'
    instance_id:
      type: string
      label: 'Instance ID'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Encrypted Password'
    access_token:
      type: string
      label: 'Encrypted Access Token'
